- frontRepo/admin/common/admin-sidebar.css
- frontRepo/admin/common/admin-sidebar.html
민상훈/1123-01/admin-common-sidebar
> 민상훈/1123-01/사이드바

- frontRepo/admin/css/msh/enrollProduct.css
- frontRepo/admin/html/msh/enrollProduct.html
- frontRepo/admin/js/msh/enrollProduct.js
> 민상훈/1124-01/상품등록(작업중)

- frontRepo/admin/common/service_center_sidebar.css
- frontRepo/admin/common/service_center_sidebar.html
> 오의정_1124_사이드바

- frontRepo/user/html/lkm/home.html
- frontRepo/user/html/lkm/login.html
> [이경민/1124_02/home, login]

- frontRepo/user/html/ouj/리뷰게시글.css
- frontRepo/user/html/ouj/리뷰게시글.html
- frontRepo/user/html/ouj/리뷰작성.css
- frontRepo/user/html/ouj/리뷰작성.html
> [오의정] 리뷰게시글, 리뷰 작성 화면 작업

- frontRepo/admin/css/msh/enrollProduct.css
- frontRepo/admin/html/msh/enrollProduct.html
- frontRepo/admin/js/msh/enrollProduct.js
> 민상훈/1127-01/상품등록

- frontRepo/user/css/lkm/join.css
- frontRepo/user/css/lkm/my_selllist.css
- frontRepo/user/css/lkm/my_shoplist.css
- frontRepo/user/css/lkm/my_wishlist.css
- frontRepo/user/html/lkm/join.html
- frontRepo/user/html/lkm/my_selllist.html
- frontRepo/user/html/lkm/my_shoplist.html
- frontRepo/user/html/lkm/my_wishlist.html
* 회원가입수정
* 관심상품 작업 중
* 구매내역 판매내역 완료
> Lgm1127 02

- frontRepo/user/css/kty/check.css
- frontRepo/user/html/kty/Purchase.html
- frontRepo/user/html/kty/check.html
> 곽태윤_1127_02 두 번쨰 구매하기 페이지 구현중

- frontRepo/user/common/footer.html
- frontRepo/user/common/popUp.html
- frontRepo/user/common/popup1.html
- frontRepo/user/common/popup2.html
- frontRepo/user/html/lkp/notice.html
> 이광포_1127_02 [notice만드는중]

- frontRepo/admin/common/servicecenterside.css
- frontRepo/admin/common/servicecenterside.html
- frontRepo/user/css/ouj/review_board.css
- frontRepo/user/css/ouj/review_list.css
- frontRepo/user/css/ouj/review_write.css
- frontRepo/user/html/ouj/review_board.html
- frontRepo/user/html/ouj/review_list.html
- frontRepo/user/html/ouj/review_write.html
> 오의정_1127_02 리뷰 게시글 / 작성

- frontRepo/admin/css/lkm/admin_searchID_result.css
- frontRepo/admin/css/lkm/adminsearchID.css
- frontRepo/admin/html/lkm/admin_searchID_result.html
- frontRepo/admin/html/lkm/adminsearchID.html
- frontRepo/user/css/lkm/my_point.css
- frontRepo/user/css/lkm/my_wishlist.css
- frontRepo/user/css/lkm/searchID.css
- frontRepo/user/css/lkm/searchID_result.css
- frontRepo/user/html/lkm/my_point.html
- frontRepo/user/html/lkm/my_wishlist.html
- frontRepo/user/html/lkm/searchID.html
- frontRepo/user/html/lkm/searchID_result.html
* 관리자 유저 아이디 찾기 css
* 마이페이지 관심상품 css
* 마이페이지 포인트 css
> Lgm1128 01

- frontRepo/admin/common/servicecenterside.css
- frontRepo/user/css/lkp/notice.css
- frontRepo/user/html/lkp/notice.html
> 이광포_1128_01 [공지사항 만드는중.. ㅜㅜ]

- frontRepo/user/css/kty/check.css
- frontRepo/user/html/kty/checkcopy.html
> 곽태윤_1128_01 구매동의 페이지 작성중

- frontRepo/user/css/ouj/review_board.css
> 오의정_1128_01 리뷰게시판 css 수정

- frontRepo/admin/css/lkm/admin_login.css
- frontRepo/admin/css/lkm/admin_searchPwd.css
- frontRepo/admin/css/lkm/admin_searchPwd_result.css
- frontRepo/admin/html/lkm/admin_login.html
- frontRepo/admin/html/lkm/admin_searchPwd.html
- frontRepo/admin/html/lkm/admin_searchPwd_result.html
- frontRepo/user/common/maintab.css
- frontRepo/user/common/maintab.html
- frontRepo/user/common/mypagemenu.css
- frontRepo/user/common/mypagemenu.html
- frontRepo/user/common/userheader.css
- frontRepo/user/common/userheader.html
- frontRepo/user/css/lkm/home.css
- frontRepo/user/css/lkm/join.css
- frontRepo/user/css/lkm/login.css
- frontRepo/user/css/lkm/my_info.css
- frontRepo/user/css/lkm/quit(modal).css
- frontRepo/user/css/lkm/searchPwd.css
- frontRepo/user/css/lkm/searchPwd_result.css
- frontRepo/user/html/lkm/home.html
- frontRepo/user/html/lkm/join.html
- frontRepo/user/html/lkm/login.html
- frontRepo/user/html/lkm/my_info.html
- frontRepo/user/html/lkm/quit(modal).html
- frontRepo/user/html/lkm/searchPwd.html
- frontRepo/user/html/lkm/searchPwd_result.html
* 유저 관리자 비밀번호 찾기
* 관리자 로그인
* 로그인 정보
* 회원탈퇴 모달
* 유저 header css 설정값 수정 다른 파일도 모두 수정할 예정
> Lgm1128 02

- frontRepo/user/css/lkm/join.css
- frontRepo/user/html/lkm/join.html
- frontRepo/user/js/lkm/join.js
* 회원가입 js 작업 위해 html css 코드 수정
* js 작업 시작
> 이경민 1129 회원가입 js 작업 시작

- frontRepo/user/css/ouj/review_board.css
- frontRepo/user/css/ouj/review_list.css
- frontRepo/user/html/ouj/review_board.html
- frontRepo/user/html/ouj/review_list.html
> 오의정_1129_01 리뷰조회 수정

- frontRepo/admin/common/admin-sidebar.css
- frontRepo/admin/common/admin-sidebar.html
- frontRepo/user/css/msh/product.css
- frontRepo/user/html/msh/product.html
민상훈/1129-01/관리자 왼쪽메뉴 수정, 조건검색 수정
> 민상훈/1129-01/관리자 왼쪽메뉴 수정, 조건검색 수정

- frontRepo/user/css/msh/product.css
- frontRepo/user/html/msh/product.html
- frontRepo/user/html/msh/sorting.svg
> 민상훈/1129-02/조건검색 진행중

- .gitignore
- frontRepo/user/common/mypagemenu.css
- frontRepo/user/css/lkm/my_point.css
- frontRepo/user/html/lkm/join.html
- frontRepo/user/html/lkm/my_point.html
- frontRepo/user/js/lkm/join.js
- wasRepo/team4_shoekream/src/main/java/com/shoekream/home/HomeController.java
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/home.jsp
* html css 자잘수정
* js 조금 작업
* wasRepo 폴더 생성 테스트파일... 살포시,,, 그리고 gitignore수정
> Lgm1129 02

- frontRepo/user/css/ouj/review_board.css
- frontRepo/user/css/ouj/review_list.css
- frontRepo/user/css/ouj/review_write.css
- frontRepo/user/html/ouj/review_board.html
- frontRepo/user/html/ouj/review_list.html
- frontRepo/user/html/ouj/review_write.html
euijeong_1129_02 리뷰게시글 추가 / 리뷰목록 리뷰작성 살짝씩 수정
> euijeong_1129_02 리뷰게시글 추가 / 리뷰목록 리뷰작성 살짝씩 수정

- frontRepo/admin/html/lkp/notice_admin.html
> 이광포_1129_02_관리자 공지사항 수정중

- frontRepo/user/css/kty/buy/buy.css
> 곽태윤_1129_02 즉시구매하기 완성해감

- frontRepo/admin/common/footer.css
- frontRepo/admin/common/footer.html
- frontRepo/admin/css/lkp/notice_admin.css
- frontRepo/admin/html/lkp/notice_admin.html
- frontRepo/admin/html/lkp/notice_admin_detail.html
- frontRepo/user/css/lkp/faq.css
- frontRepo/user/css/lkp/notice.css
- frontRepo/user/css/lkp/notice_detail.css
- frontRepo/user/html/lkp/faq.html
- frontRepo/user/html/lkp/notice.html
- frontRepo/user/html/lkp/notice_detail.html
> 이광포_1130_01 [공지사항 유저 상세페이지 완성, 관리자 상세페이지 진행중]

- frontRepo/user/css/ouj/review_board.css
- frontRepo/user/css/ouj/review_list.css
- frontRepo/user/css/ouj/review_write.css
- frontRepo/user/html/ouj/review_board.html
- frontRepo/user/html/ouj/review_list.html
- frontRepo/user/html/ouj/review_write.html
> euijeong_1130_보드 수정

- frontRepo/user/css/kty/sell/sell.css
- frontRepo/user/html/kty/sell/sell.html
> 곽태윤_1130_02 즉시구매, 즉시판매 거의 완료

- frontRepo/admin/common/service_center_side.css
- frontRepo/admin/common/service_center_side.html
- frontRepo/user/css/ouj/review_board.css
- frontRepo/user/css/ouj/review_comment.css
- frontRepo/user/css/ouj/review_list.css
- frontRepo/user/css/ouj/review_write.css
- frontRepo/user/html/ouj/review_board.html
- frontRepo/user/html/ouj/review_comment.html
- frontRepo/user/html/ouj/review_list.html
- frontRepo/user/html/ouj/review_write.html
> euijeong_1130_02 리뷰댓글작성 시작

- wasRepo/team4_shoekream/src/main/java/com/shoekream/mypage/controller/BuyingListController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/mypage/controller/MyPageController.java
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/common/mypage_side.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/member/join.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/mypage/buying.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/mypage/my.jsp
- wasRepo/team4_shoekream/src/main/webapp/resources/css/common/mypage_side.css
- wasRepo/team4_shoekream/src/main/webapp/resources/css/member/join.css
- wasRepo/team4_shoekream/src/main/webapp/resources/css/mypage/my.css
- wasRepo/team4_shoekream/src/main/webapp/resources/js/member/join.js
- wasRepo/team4_shoekream/src/main/webapp/resources/js/mypage/my.js
* 회원가입 js
* 파일 준비
* 마이페이지 프로필 사진 filereader 활용 js
> Lgm1201 01

- frontRepo/user/css/kty/sell/sell.css
- frontRepo/user/html/kty/sell/sell.html
> 곽태윤_1201_01 입찰페이지 구현중

- .gitignore
- .vscode/settings.json
- Servers/Tomcat v9.0 Server at localhost-config/catalina.policy
- Servers/Tomcat v9.0 Server at localhost-config/catalina.properties
- Servers/Tomcat v9.0 Server at localhost-config/context.xml
- Servers/Tomcat v9.0 Server at localhost-config/server.xml
- Servers/Tomcat v9.0 Server at localhost-config/tomcat-users.xml
- Servers/Tomcat v9.0 Server at localhost-config/web.xml
- frontRepo/user/css/ouj/review_comment.css
- frontRepo/user/html/ouj/review_board.html
- frontRepo/user/html/ouj/review_comment.html
> 오의정_1201_01 댓글 작업중

- wasRepo/team4_shoekream/src/main/java/com/shoekream/db/util/JDBCTemplate.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/filter/EncodingFilter.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/member/MemberVo.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/member/controller/MemberLoginController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/member/dao/MemberDao.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/member/service/MemberService.java
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/common/header.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/member/login.jsp
- wasRepo/team4_shoekream/src/main/webapp/resources/css/member/login.css
- wasRepo/team4_shoekream/src/main/webapp/resources/js/member/join.js
- wasRepo/team4_shoekream/src/main/webapp/resources/js/member/login.js
* jdbctemplate, encodingfilter 작업
* 자체 로그인 기능 구현 완료
* 회원가입 js 자잘수정
> Lgm1201 02

- frontRepo/user/html/kty/buy/bidding.html
- wasRepo/team4_shoekream/src/main/java/com/shoekream/bidding/BiddingVo.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/bidding/controller/BuyCheckController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/bidding/controller/BuyNowControlloer.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/bidding/controller/BuySelectController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/bidding/controller/BuybiddingControlloer.java
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/buy/bidding.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/buy/check.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/buy/now.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/buy/select.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/sell/bidding.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/sell/check.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/sell/now.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/sell/select.jsp
> 곽태윤_1201_02 입찰페이지 구현중, 서블릿/JSP 구현중

- frontRepo/user/css/ouj/review_comment.css
- frontRepo/user/css/ouj/review_list.css
- frontRepo/user/css/ouj/review_write.css
- frontRepo/user/html/ouj/review_comment.html
- frontRepo/user/html/ouj/review_list.html
- frontRepo/user/html/ouj/review_write.html
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/review/write.jsp
> 오의정_1201_review write js 시작..

- frontRepo/user/css/kty/buy/bidding.css
- frontRepo/user/html/kty/buy/bidding.html
- wasRepo/team4_shoekream/src/main/java/com/shoekream/bidding/controller/SellCheckController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/bidding/controller/SellNowControlloer.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/bidding/controller/SellSelectController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/bidding/controller/SellbiddingControlloer.java
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/sell/bidding.jsp
> Kty 1202 01

- wasRepo/team4_shoekream/src/main/java/com/shoekream/review/controller/ReviewWriteController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/review/dao/ReviewDao.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/review/service/ReviewService.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/review/vo/ReviewVo.java
> euijeong_1202_01 리뷰 목록 js

- frontRepo/user/css/kty/buy/now.css
- frontRepo/user/css/kty/buy/sattle.css
- frontRepo/user/css/kty/sell/bidding.css
- frontRepo/user/html/kty/buy/now.html
- frontRepo/user/html/kty/buy/sattle.html
- frontRepo/user/html/kty/sell/bidding.html
> 곽태윤_1203_01 결제/정산 페이지 구현중

- frontRepo/user/css/ouj/product_request_detail.css
- frontRepo/user/html/ouj/product_request_detail.html
- wasRepo/team4_shoekream/src/main/java/com/shoekream/admin/controller/AdminEnrollProductController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/review/controller/ReviewListController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/review/controller/ReviewWriteController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/review/dao/ReviewDao.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/review/service/ReviewService.java
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/review/error.jsp
> euijeong_1204_01 리뷰 목록 조회js

- frontRepo/admin/css/lkp/notice_admin_detail.css
- frontRepo/admin/html/lkp/notice_admin_detail.html
- frontRepo/user/html/lkp/notice_detail.html
> 이광포_1204_01[CSS수정]

- wasRepo/team4_shoekream/src/main/java/com/shoekream/bidding/dao/BuySelectDao.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/bidding/service/BuySelectService.java
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/buy/bidding.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/buy/biddingpayment.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/buy/check.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/buy/now.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/buy/nowpayment.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/buy/select.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/sell/bidding.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/sell/biddingsattle.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/sell/check.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/sell/now.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/sell/nowsattle.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/sell/select.jsp
- wasRepo/team4_shoekream/src/main/webapp/resources/css/bidding/buy/biddingpayment.css
> 곽태윤_1204_02 쿼리문..

- frontRepo/admin/html/msh/editProduct.html
- frontRepo/admin/html/msh/enrollProduct.html
- wasRepo/team4_shoekream/src/main/java/com/shoekream/admin/controller/AdminEnrollProductController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/admin/dao/AdminEnrollProductDao.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/admin/service/AdminEnrollProductService.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/admin/vo/EnrollProductVo.java
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/admin/product/enroll.jsp
> 민상훈/1204-02/상품등록페이지 서버작업

- frontRepo/user/html/ouj/product_request_list.html
- wasRepo/team4_shoekream/src/main/java/com/shoekream/page/vo/PageVo.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/review/controller/ReviewWriteController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/review/dao/ReviewDao.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/review/service/ReviewService.java
euijeong_1204_02 리뷰 목록조회 아주 살짝 수정
> euijeong_1204_02 리뷰 목록조회 아주 살짝 수정

- wasRepo/team4_shoekream/src/main/java/com/shoekream/admin/controller/AdminEnrollProductController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/admin/dao/AdminEnrollProductDao.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/admin/vo/EnrollProductVo.java
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/admin/product/enroll.jsp
> 민상훈/1205-01/상품등록 수정

- frontRepo/admin/css/lkp/notice_admin.css
- frontRepo/admin/css/lkp/notice_admin_detail_edit.css
- frontRepo/admin/css/lkp/notice_admin_detail_edit_complete.css
- frontRepo/admin/html/lkp/notice_admin.html
- frontRepo/admin/html/lkp/notice_admin_detail_edit.html
- frontRepo/admin/html/lkp/notice_admin_detail_write.html
- frontRepo/user/common/popup2.html
- frontRepo/user/css/lkp/notice.css
- frontRepo/user/css/lkp/notice_detail.css
- frontRepo/user/html/lkp/notice.html
- frontRepo/user/html/lkp/notice_detail.html
- wasRepo/team4_shoekream/src/main/java/com/shoekream/notice/Ex.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/notice/controller/BoardController.java
> 이광포_1205_01 [공지사항 css 최종 수정(?), 팝업창 2개]

- wasRepo/team4_shoekream/src/main/java/com/shoekream/mypage/controller/MyPageMainController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/mypage/dao/BuyingListDao.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/mypage/dao/WishListDao.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/mypage/service/BuyingListService.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/mypage/service/WishListService.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/mypage/vo/BuyingListVo.java
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/mypage/my.jsp
> 이경민/1205/파일 준비

- wasRepo/team4_shoekream/src/main/java/com/shoekream/orders/vo/OrdersVo.java
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/buy/select.jsp
- wasRepo/team4_shoekream/src/main/webapp/resources/js/bidding/buy/select.js
> 곽태윤_1205_02 BuySelect 페이지 출력 성공 !

- wasRepo/team4_shoekream/src/main/java/com/shoekream/admin/controller/AdminEnrollProductController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/admin/dao/AdminEnrollProductDao.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/admin/service/AdminEnrollProductService.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/admin/vo/EnrollProductVo.java
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/admin/product/enroll.jsp
> 민상훈/1205-02/상품등록 작업중

- frontRepo/user/css/ouj/product_request_detail.css
- frontRepo/user/css/ouj/product_request_list.css
- frontRepo/user/css/ouj/review_list.css
- frontRepo/user/html/ouj/product_request_detail.html
- frontRepo/user/html/ouj/review_list.html
- wasRepo/team4_shoekream/src/main/java/com/shoekream/review/controller/MyReviewListController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/review/controller/ReviewListController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/review/controller/ReviewWriteController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/review/dao/ReviewDao.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/review/service/ReviewService.java
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/review/write.jsp
> euijeong_1206_01 리뷰 목록 수정 중

- wasRepo/team4_shoekream/src/main/java/com/shoekream/member/controller/EmailSendController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/mypage/controller/BuyingListController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/mypage/controller/MyPageMainController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/mypage/dao/BuyingListDao.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/mypage/dao/MyPageDao.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/mypage/dao/WishListDao.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/mypage/service/BuyingListService.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/mypage/service/MyPageService.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/mypage/vo/SellingListVo.java
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/member/join.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/mypage/buying.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/mypage/my.jsp
- wasRepo/team4_shoekream/src/main/webapp/resources/css/mypage/buying.css
- wasRepo/team4_shoekream/src/main/webapp/resources/js/member/join.js
- wasRepo/team4_shoekream/src/main/webapp/resources/js/mypage/buying.js
* 이메일 인증 구현 중(MimeMessage 생성이 왜 안되나...)
* 마이페이지 구매내역 작업 중
* vo 준비
> Lgm1206 01

- frontRepo/user/common/footer.html
- wasRepo/team4_shoekream/src/main/java/com/shoekream/notice/controller/NoticeListController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/notice/controller/NoticeVo.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/notice/dao/NoticeDao.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/notice/service/NoticeService.java
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/board/notice/notice_member.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/common/footer.jsp
- wasRepo/team4_shoekream/src/main/webapp/resources/css/board/notice/notice.css
- wasRepo/team4_shoekream/src/main/webapp/resources/css/common/footer.css
> 이광포_1206_01 [공지사항 백엔드 작업중, footer 완료]

- wasRepo/team4_shoekream/src/main/java/com/shoekream/admin/controller/AdminEnrollProductController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/admin/dao/AdminEnrollProductDao.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/admin/service/AdminEnrollProductService.java
> 민상훈/1206-01/상품등록

- wasRepo/team4_shoekream/src/main/java/com/shoekream/mypage/controller/BuyingBiddingController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/mypage/controller/BuyingListController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/mypage/dao/MyPageDao.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/mypage/service/MyPageService.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/mypage/vo/HistoryCntVo.java
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/common/header.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/common/mypage_side.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/mypage/buying.jsp
- wasRepo/team4_shoekream/src/main/webapp/resources/css/mypage/buying.css
- wasRepo/team4_shoekream/src/main/webapp/resources/js/mypage/buying.js
* header mypagemenu css파일 연결
* 구매내역 판매내역 조회 작업중...
> Lgm1206 02

- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/buy/bidding.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/buy/biddingpayment.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/buy/check.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/buy/now.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/buy/nowpayment.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/buy/select.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/sell/bidding.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/sell/biddingsattle.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/sell/check.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/sell/now.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/sell/nowsattle.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/sell/select.jsp
- wasRepo/team4_shoekream/src/main/webapp/resources/js/bidding/buy/select.js
> 곽태윤_1206_02 풋터 CSS 연결

- wasRepo/team4_shoekream/src/main/java/com/shoekream/notice/controller/NoticeListController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/notice/dao/NoticeDao.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/notice/service/NoticeService.java
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/board/notice/notice_member.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/common/fail.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/common/footer.jsp
> 이광포_1206_02 [공지사항 메인페이지 백엔드 작업중]

- wasRepo/team4_shoekream/src/main/java/com/shoekream/admin/controller/AdminProductLIstController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/admin/service/AdminProductListService.java
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/admin/common/admin_sidebar.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/admin/product/enroll.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/admin/product/list.jsp
- wasRepo/team4_shoekream/src/main/webapp/resources/css/admin/common/admin_sidebar.css
> 민상훈/1206-02/상품등록,목록

- frontRepo/user/css/lkp/notice.css
- frontRepo/user/html/lkp/notice_member.html
- wasRepo/team4_shoekream/src/main/java/com/shoekream/notice/controller/NoticeListController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/notice/dao/NoticeDao.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/notice/service/NoticeService.java
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/board/notice/notice_member.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/common/footer.jsp
- wasRepo/team4_shoekream/src/main/webapp/resources/css/board/notice/notice.css
> 이광포_1207_01_[공지사항 메인페이지 페이징 작업중]

- wasRepo/team4_shoekream/src/main/java/com/shoekream/biddingVo/BiddingVo.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/orders/vo/OrdersVo.java
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/buy/check.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/buy/check.jsp.rej
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/buy/select.jsp
> Kty 1207 01

- wasRepo/team4_shoekream/src/main/java/com/shoekream/member/controller/EmailSendController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/mypage/controller/BuyingBiddingController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/mypage/controller/BuyingBiddingPeriodController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/mypage/controller/BuyingController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/mypage/controller/WishListController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/mypage/dao/MyPageDao.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/mypage/service/MyPageService.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/mypage/vo/HistoryCntVo.java
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/common/mypage_side.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/member/quit.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/member/quit_modal.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/mypage/buy_buying.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/mypage/buy_finished.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/mypage/buy_pending.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/mypage/buying.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/mypage/wishlist.jsp
- wasRepo/team4_shoekream/src/main/webapp/resources/css/member/quit.css
- wasRepo/team4_shoekream/src/main/webapp/resources/css/member/quit_modal.css
- wasRepo/team4_shoekream/src/main/webapp/resources/css/mypage/buy_buying.css
- wasRepo/team4_shoekream/src/main/webapp/resources/css/mypage/buy_finished.css
- wasRepo/team4_shoekream/src/main/webapp/resources/css/mypage/buy_pending.css
- wasRepo/team4_shoekream/src/main/webapp/resources/css/mypage/buying.css
- wasRepo/team4_shoekream/src/main/webapp/resources/js/member/quit.js
- wasRepo/team4_shoekream/src/main/webapp/resources/js/mypage/buying.js
> Lgm1207 02

- wasRepo/team4_shoekream/src/main/java/com/shoekream/notice/controller/NoticeDetailController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/notice/controller/NoticeListController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/notice/dao/NoticeDao.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/page/vo/PageVo.java
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/board/notice/detail.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/board/notice/list.jsp
> 이광포_1207_02 [공지사항 메인페이지 완성..(?) 억까 그만해!]

- frontRepo/admin/common/admin-sidebar.css
- frontRepo/admin/css/msh/list.css
- frontRepo/admin/html/msh/list.html
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/admin/product/enroll.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/admin/product/list.jsp
- wasRepo/team4_shoekream/src/main/webapp/resources/css/admin/common/admin_sidebar.css
- wasRepo/team4_shoekream/src/main/webapp/resources/css/admin/product/enroll.css
- wasRepo/team4_shoekream/src/main/webapp/resources/css/admin/product/list.css
> 민상훈/1206-02/상품등록목록 수정

- frontRepo/user/css/ouj/review_write.css
- frontRepo/user/html/ouj/review_write.html
- wasRepo/team4_shoekream/src/main/java/com/shoekream/review/controller/ReviewWriteController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/review/dao/ReviewCommentDao.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/review/dao/ReviewDao.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/review/service/ReviewCommentService.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/review/service/ReviewService.java
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/common/service_center_side.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/review/write.jsp
- wasRepo/team4_shoekream/src/main/webapp/resources/css/review/write.css
euijeong_1207_02 리뷰 작성 서비스 사이드바
> euijeong_1207_02 리뷰 작성 서비스 사이드바

- wasRepo/team4_shoekream/src/main/java/com/shoekream/admin/controller/AdminProductLIstController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/admin/dao/AdminEnrollProductDao.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/admin/service/AdminProductListService.java
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/admin/product/enroll.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/admin/product/list.jsp
> 민상훈/1208-01/상품목록조회

- wasRepo/team4_shoekream/src/main/java/com/shoekream/member/controller/EmailSendController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/mypage/controller/BuyingBiddingController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/mypage/controller/BuyingController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/mypage/controller/BuyingFinishedController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/mypage/controller/BuyingPendingController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/mypage/controller/MyPageMainController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/mypage/dao/MyPageDao.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/mypage/service/MyPageService.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/mypage/vo/OrdersHistoryVo.java
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/mypage/buying.jsp
- wasRepo/team4_shoekream/src/main/webapp/resources/js/mypage/buying.js
> Lgm1208 02

- wasRepo/team4_shoekream/src/main/java/com/shoekream/admin/controller/AdminProductLIstController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/admin/vo/EnrollProductVo.java
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/admin/product/list.jsp
> 민상훈/1208-02/상품등록,리스트조회

- frontRepo/user/css/lkp/notice.css
- frontRepo/user/css/lkp/notice_detail.css
- frontRepo/user/html/lkp/notice_member.html
- frontRepo/user/html/lkp/notice_member_detail.html
- wasRepo/team4_shoekream/src/main/java/com/shoekream/notice/controller/NoticeListController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/notice/controller/NoticeSearchController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/notice/dao/NoticeDao.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/notice/service/NoticeService.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/notice/vo/NoticeVo.java
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/board/notice/detail.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/board/notice/list.jsp
- wasRepo/team4_shoekream/src/main/webapp/resources/css/board/notice/detail.css
- wasRepo/team4_shoekream/src/main/webapp/resources/css/board/notice/list.css
> 이광포_1208_02 [공지사항 검색기능 구현중.....]

- frontRepo/user/html/lkm/my_shoplist.html
- wasRepo/team4_shoekream/src/main/java/com/shoekream/member/AuthenticationKey.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/member/MemberVo.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/member/controller/EmailSendController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/member/controller/MemberJoinController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/member/dao/MemberDao.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/member/service/MemberService.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/mypage/controller/BuyingFinishedController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/mypage/controller/BuyingPendingController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/mypage/controller/MainProfileImageController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/mypage/controller/MyPageMainController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/mypage/controller/SellingController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/mypage/dao/MyPageDao.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/mypage/service/MyPageService.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/mypage/vo/WishListVo.java
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/common/mypage_side.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/member/join.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/member/login.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/mypage/my.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/mypage/my_popup.jsp
- wasRepo/team4_shoekream/src/main/webapp/resources/css/member/join.css
- wasRepo/team4_shoekream/src/main/webapp/resources/js/member/join.js
- wasRepo/team4_shoekream/src/main/webapp/resources/js/mypage/buying.js
- wasRepo/team4_shoekream/src/main/webapp/resources/js/mypage/my.js
* 구매내역 완료
* 판매내역 시작
* 마이페이지 메인 프로필사진 변경 구현 중
* 회원가입 인증번호 구현 중
> Lgm1209 01

- wasRepo/team4_shoekream/src/main/java/com/shoekream/notice/controller/AdminNoticeDeleteController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/notice/controller/AdminNoticeDetailController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/notice/controller/AdminNoticeEditController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/notice/controller/AdminNoticeListController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/notice/controller/AdminNoticeWriteController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/notice/controller/NoticeSearchController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/notice/dao/NoticeDao.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/notice/service/NoticeService.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/page/vo/PageVo.java
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/admin/board/notice/adminDetail.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/admin/board/notice/adminList.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/admin/board/notice/adminWrite.jsp
- wasRepo/team4_shoekream/src/main/webapp/resources/css/admin/board/notice/admin_detail.css
- wasRepo/team4_shoekream/src/main/webapp/resources/css/admin/board/notice/admin_edit.css
- wasRepo/team4_shoekream/src/main/webapp/resources/css/admin/board/notice/admin_list.css
> 이광포_1209_01 [공지사항 검색기능 추가 및 관리자모드 게시판 생성 기능 추가, 게시글 수정& 삭제는 작업중..]

- frontRepo/admin/html/lkp/notice_admin_detail_write.html
- wasRepo/team4_shoekream/src/main/java/com/shoekream/notice/Ex.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/notice/controller/AdminNoticeDeleteController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/notice/controller/AdminNoticeEditController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/notice/controller/AdminNoticeSearchController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/notice/controller/AdminNoticeWriteController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/notice/dao/NoticeDao.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/qna/controller/QnaListController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/qna/dao/QnaDao.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/qna/service/QnaService.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/qna/vo/QnaVo.java
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/admin/board/notice/adminDetail.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/admin/board/notice/adminEdit.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/admin/board/notice/adminList.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/common/footer.jsp
- wasRepo/team4_shoekream/src/main/webapp/resources/css/admin/board/notice/admin_detail.css
- wasRepo/team4_shoekream/src/main/webapp/resources/css/admin/board/notice/admin_edit.css
- wasRepo/team4_shoekream/src/main/webapp/resources/css/admin/board/notice/admin_list.css
> 이광포_1210_01 [공지사항 멤버/관리자 완성/ QNA CSS+백엔드 작업중]

- frontRepo/admin/html/lkp/notice_admin_detail.html
- wasRepo/team4_shoekream/src/main/java/com/shoekream/notice/controller/AdminNoticeWriteController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/qna/controller/QnaDetailController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/qna/controller/QnaSearchController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/qna/controller/QnaWriteController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/qna/dao/QnaDao.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/qna/service/QnaService.java
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/admin/board/qna/adminList.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/board/qna/detail.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/board/qna/list.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/board/qna/write.jsp
- wasRepo/team4_shoekream/src/main/webapp/resources/css/board/qna/detail.css
- wasRepo/team4_shoekream/src/main/webapp/resources/css/board/qna/edit.css
- wasRepo/team4_shoekream/src/main/webapp/resources/css/board/qna/list.css
- wasRepo/team4_shoekream/src/main/webapp/resources/css/common/footer.css
> 이광포_1211_01 [QNA 작업중..]

- wasRepo/team4_shoekream/src/main/java/com/shoekream/admin/dao/AdminEnrollProductDao.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/admin/service/AdminProductListService.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/product/controller/ProductController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/product/controller/ProductDetailController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/product/dao/ProductDetailDao.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/product/service/ProductDetailService.java
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/product/detail.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/product/product.jsp
> 민상훈/1211-02/상품상세정보..

- wasRepo/team4_shoekream/src/main/java/com/shoekream/qna/controller/AdminQnaDetailController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/qna/controller/AdminQnaListController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/qna/controller/QnaWriteController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/qna/dao/QnaDao.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/qna/vo/QnaVo.java
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/admin/board/notice/adminEdit.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/admin/board/notice/adminList.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/admin/board/notice/adminWrite.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/admin/board/qna/adminDetail.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/admin/board/qna/adminList.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/board/notice/list.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/board/qna/list.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/board/qna/write.jsp
- wasRepo/team4_shoekream/src/main/webapp/resources/css/admin/board/notice/admin_edit.css
- wasRepo/team4_shoekream/src/main/webapp/resources/css/admin/board/qna/admin_detail.css
- wasRepo/team4_shoekream/src/main/webapp/resources/css/admin/board/qna/admin_list.css
- wasRepo/team4_shoekream/src/main/webapp/resources/css/board/qna/detail.css
> LKP_1211_02 [QNA 작업중2....]

- wasRepo/team4_shoekream/src/main/java/com/shoekream/bidding/controller/BuyBiddingControlloer.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/bidding/controller/BuyNowPaymentControlloer.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/bidding/controller/orderController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/bidding/dao/BiddingDao.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/bidding/service/BiddingService.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/orders/vo/OrdersVo.java
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/buy/bidding.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/buy/nowpayment.jsp
- wasRepo/team4_shoekream/src/main/webapp/resources/js/bidding/buy/bidding.js
> 곽태윤_1211_02 구매 쪽 js 구현 완료, 오류 해결 완료ㅋ 기능 구현 중

- wasRepo/team4_shoekream/src/main/java/com/shoekream/bidding/controller/BuyBiddingControlloer.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/bidding/controller/BuyNowControlloer.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/bidding/controller/orderController.java
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/buy/bidding.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/buy/biddingpayment.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/buy/now.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/buy/order.jsp
- wasRepo/team4_shoekream/src/main/webapp/resources/css/bidding/buy/bidding.css
- wasRepo/team4_shoekream/src/main/webapp/resources/js/bidding/buy/bidding.js
> Kty 1212 01

- wasRepo/team4_shoekream/src/main/java/com/shoekream/admin/controller/AdminEnrollProductController.java
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/product/product.jsp
> 민상훈/1212-02/상품페이지 오류수정

- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/admin/board/notice/adminList.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/common/footer.jsp
> 이광포_1212_02 [오후작업..]

- wasRepo/team4_shoekream/src/main/java/com/shoekream/bidding/controller/BiddingOrderController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/bidding/controller/BuyBiddingControlloer.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/bidding/controller/BuyBiddingPaymentControlloer.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/bidding/controller/BuyCheckController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/bidding/controller/BuyNowControlloer.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/bidding/controller/BuyNowPaymentControlloer.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/bidding/controller/BuySelectController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/bidding/controller/OrderController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/bidding/dao/BiddingDao.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/bidding/service/BiddingService.java
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/buy/bidding.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/buy/biddingorder.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/buy/biddingpayment.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/buy/nowpayment.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/buy/selectproduct.jsp
- wasRepo/team4_shoekream/src/main/webapp/resources/css/bidding/buy/bidding.css
- wasRepo/team4_shoekream/src/main/webapp/resources/css/bidding/buy/biddingorder.css
- wasRepo/team4_shoekream/src/main/webapp/resources/css/bidding/buy/biddingpayment.css
- wasRepo/team4_shoekream/src/main/webapp/resources/js/bidding/buy/bidding.js
- wasRepo/team4_shoekream/src/main/webapp/resources/js/bidding/order.js
> 곽태윤_1213_01 구매입찰 INSERT 구현중

- wasRepo/team4_shoekream/src/main/java/com/shoekream/faq/dao/FaqDao.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/qna/controller/AdminQnaListController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/qna/dao/QnaDao.java
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/admin/board/faq/adminDetail.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/admin/board/faq/adminList.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/admin/board/qna/adminList.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/board/faq/detail.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/board/faq/list.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/board/qna/detail.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/board/qna/list.jsp
- wasRepo/team4_shoekream/src/main/webapp/resources/css/admin/board/faq/admin_detail.css
- wasRepo/team4_shoekream/src/main/webapp/resources/css/admin/board/faq/admin_list.css
- wasRepo/team4_shoekream/src/main/webapp/resources/css/board/faq/detail.css
- wasRepo/team4_shoekream/src/main/webapp/resources/css/board/faq/list.css
- wasRepo/team4_shoekream/src/main/webapp/resources/css/board/qna/list.css
> 이광포_1213_02 [ qna list, faq 조회수 기능 추가]

- wasRepo/team4_shoekream/src/main/java/com/shoekream/bidding/controller/SellNowControlloer.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/bidding/dao/BiddingDao.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/bidding/service/BiddingService.java
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/buy/now.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/sell/check.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/sell/now.jsp
- wasRepo/team4_shoekream/src/main/webapp/resources/css/bidding/buy/check.css
- wasRepo/team4_shoekream/src/main/webapp/resources/css/bidding/sell/check.css
- wasRepo/team4_shoekream/src/main/webapp/resources/js/bidding/sell/check.js
> 곽태윤_1214_01 즉시판매 페이지 구현중

- wasRepo/team4_shoekream/src/main/java/com/shoekream/admin/dao/AdminEnrollProductDao.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/product/controller/ProductController.java
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/product/detail.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/product/product.jsp
> 민상훈/1213-03/상품조건검색..

- wasRepo/team4_shoekream/src/main/java/com/shoekream/product/controller/ProductDetailController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/product/dao/ProductDetailDao.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/product/service/ProductDetailService.java
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/product/detail.jsp
> 민상훈/1213-04/관심상품등록

- wasRepo/team4_shoekream/src/main/java/com/shoekream/request/controller/RequestDetailController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/request/controller/RequestEditController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/request/controller/RequestListController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/request/controller/RequestSearchController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/request/controller/RequestWriteController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/request/dao/RequestDao.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/request/service/RequestService.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/request/vo/RequestVo.java
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/board/request/detail.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/board/request/list.jsp
- wasRepo/team4_shoekream/src/main/webapp/resources/css/board/request/detail.css
> LKP_1213_03 [상품등록요청 게시판 작업중..]

- wasRepo/team4_shoekream/src/main/java/com/shoekream/bidding/controller/SellNowControlloer.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/bidding/dao/BiddingDao.java
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/sell/now.jsp
> 곽태윤_1214_01 즉시판매하기 페이지 완료 -> 폼태그 연결

- wasRepo/team4_shoekream/src/main/java/com/shoekream/admin/controller/AdminEnrollProductController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/admin/controller/AdminProductEditController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/admin/controller/AdminProductLIstController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/product/controller/ProductDetailController.java
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/admin/common/admin_sidebar.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/admin/product/enroll.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/admin/product/list.jsp
- wasRepo/team4_shoekream/src/main/webapp/resources/css/admin/common/admin_sidebar.css
- wasRepo/team4_shoekream/src/main/webapp/resources/css/admin/product/enroll.css
> 민상훈/1214-02_1/로그인확인 추가

- wasRepo/team4_shoekream/src/main/java/com/shoekream/bidding/controller/BuyNowPaymentControlloer.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/bidding/controller/BuyOrderController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/bidding/controller/SellNowControlloer.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/bidding/controller/SellNowSattleControlloer.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/bidding/controller/SellOrderController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/bidding/dao/BiddingDao.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/bidding/service/BiddingService.java
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/sell/now.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/sell/nowsattle.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/sell/order.jsp
- wasRepo/team4_shoekream/src/main/webapp/resources/css/bidding/buy/order.css
> Kty 1214 02

- wasRepo/team4_shoekream/src/main/java/com/shoekream/request/controller/RequestDeleteController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/request/controller/RequestEditController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/request/dao/RequestDao.java
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/admin/board/request/adminList.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/board/request/detail.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/board/request/edit.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/board/request/write.jsp
- wasRepo/team4_shoekream/src/main/webapp/resources/css/admin/board/faq/admin_detail.css
- wasRepo/team4_shoekream/src/main/webapp/resources/css/admin/board/faq/admin_list.css
- wasRepo/team4_shoekream/src/main/webapp/resources/css/board/request/edit.css
> 이광포_1214_02 [request 관리자 페이지 작업중]

- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/admin/common/admin_sidebar.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/admin/product/list.jsp
- wasRepo/team4_shoekream/src/main/webapp/resources/css/product/product.css
> 민상훈/1214-03/css수정

- wasRepo/team4_shoekream/src/main/java/com/shoekream/request/controller/AdminRequestDetailController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/request/controller/AdminRequestListController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/request/controller/AdminRequestSearchController.java
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/admin/board/request/adminDetail.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/admin/board/request/adminList.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/board/request/detail.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/board/request/edit.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/board/request/list.jsp
- wasRepo/team4_shoekream/src/main/webapp/resources/css/admin/board/faq/admin_detail.css
- wasRepo/team4_shoekream/src/main/webapp/resources/css/admin/board/request/admin_detail.css
- wasRepo/team4_shoekream/src/main/webapp/resources/css/admin/board/request/admin_list.css
> 이광포_1214_03 [request 거의 완료]

- wasRepo/team4_shoekream/src/main/java/com/shoekream/bidding/controller/SellBiddingOrderController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/bidding/controller/SellBiddingSattleControlloer.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/bidding/controller/SellSelectController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/bidding/dao/BiddingDao.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/bidding/service/BiddingService.java
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/sell/biddingsattle.jsp
> 판매입찰 마지막 페이지 거의 구현 완료... dbVo == null 해결 중

- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/admin/product/list.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/product/detail.jsp
- wasRepo/team4_shoekream/src/main/webapp/resources/css/admin/product/list.css
> 민상훈/1214-06/버그수정

- wasRepo/team4_shoekream/src/main/java/com/shoekream/faq/service/FaqService.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/member/controller/EmailDupCheckController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/notice/controller/NoticeListController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/qna/controller/AdminQnaSearchController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/request/controller/AdminRequestDetailController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/request/controller/AdminRequestListController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/request/controller/AdminRequestSearchController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/request/controller/RequestDeleteController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/request/controller/RequestDetailController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/request/controller/RequestEditController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/request/controller/RequestListController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/request/controller/RequestSearchController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/request/controller/RequestWriteController.java
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/board/request/detail.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/board/request/edit.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/board/request/list.jsp
> 이광포_1214_04 [최종수정?]

- wasRepo/team4_shoekream/src/main/java/com/shoekream/notice/controller/NoticeDetailController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/notice/controller/NoticeSearchController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/qna/controller/AdminQnaSearchController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/request/controller/AdminRequestSearchController.java
> 이광포_1214_05 [마지막 PR]

- wasRepo/team4_shoekream/src/main/java/com/shoekream/bidding/controller/SellBiddingOrderController.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/bidding/dao/BiddingDao.java
- wasRepo/team4_shoekream/src/main/java/com/shoekream/bidding/service/BiddingService.java
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/sell/biddingorder.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/sell/biddingsattle.jsp
- wasRepo/team4_shoekream/src/main/webapp/resources/css/bidding/sell/biddingorder.css
- wasRepo/team4_shoekream/src/main/webapp/resources/js/bidding/sell/bidding.js
> Kty 1214 04

- wasRepo/team4_shoekream/src/main/java/com/shoekream/admin/controller/AdminEnrollProductController.java
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/admin/common/admin_sidebar.jsp
- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/admin/product/list.jsp
> 민상훈/1214-07/버그수정 및 기타 수정

- wasRepo/team4_shoekream/src/main/webapp/WEB-INF/views/mypage/editAddr.jsp
> 고영대/1214-07/최최종
